var appConstants = {

    FIREBASE_HOST: "https://time-line.firebaseio.com/",
    //GET_DATA: "GET_DATA",
    //ADD_ITEM: "ADD_ITEM",
    //REMOVE_ITEM: "REMOVE_ITEM"

    CHANGE_TIMELINES: "CHANGE_TIMELINES",
    CHANGE_PUBLIC_TIMELINES: "CHANGE_PUBLIC_TIMELINES",
    EMPTY_USER_DATA: "EMPTY_USER_DATA",
    ADD_TIMELINE: "ADD_TIMELINE",
    LOAD_TIMELINE: "LOAD_TIMELINE",
    EDIT_TIMELINE: "EDIT_TIMELINE",
    ADD_DOT: "ADD_DOT",
    REMOVE_DOT: "REMOVE_DOT",

    CHANGE_BM_COUNT: 'CHANGE_BM_COUNT',
    CHANGE_BOOKMARKS: "CHANGE_BOOKMARKS",
    TOGGLE_TIMELINE_BOOKMARK: "TOGGLE_TIMELINE_BOOKMARK",

    LOGIN_USER: "LOGIN_USER",
    CHANGE_USER: "CHANGE_USER",
    LOGOUT_USER: "LOGOUT_USER"
};

module.exports = appConstants;

